### ISSUE TITLE
Failing behavior with async methods

### ISSUE THREAD

**Issue by anthonylouisbsb** [ionelmc/python-aspectlib#18]
I was running this script [test_script](https://gist.github.com/anthonylouisbsb/6cfd618b58ca0fdc581f6d81404e9674 ) to print the name and time execution for each method inside my code. Here are the results: [test_results](https://gist.github.com/anthonylouisbsb/fb11453371fe35784dd38051cde56860) 

Look that for asynchronous methods, the lib prints some garbage information in result like ` await: <coroutine object create_columns_in_bulk at 0x7f76106a0ba0>
`  or `got result from await: <shannondb.protocol.ShannonDBClientProtocol object at 0x7f76106752e8>` .Is it a misuse of library or **aspectlib** does not support async methods yet?

Here are the code for [ShannonDBClient](https://gist.github.com/anthonylouisbsb/5e97040cc44e2f87bede2c2ab0b20830) and [columns](https://gist.github.com/anthonylouisbsb/324b9b8a00ff800c194e7d2cfad9c159) module

**Comment by ionelmc** [comment]
So that `got result from await:` was some leftover I forgot. Released v1.5.1 now.
