### ISSUE TITLE
QUESTION: is it designed to wrap methods, funtions only? Can classes be wrapped?

### ISSUE THREAD

**Issue by 4l1fe** [ionelmc/python-aspectlib#28]
Hey. I'm looking for exactly the same functionality **aspectlib** provides with. You've done good job!

Can you suggest a way of how to wrap a class to have all its methods handled by aspect's logic?

Something like this
```python

def log_every_method_call(*args, **kawrgs):
    print("Call", args, kwargs)
    result = yield aspectlib.Proceed
    print("Result", result)


@log_every_method_call
class ComplexClass:
    ....
```

**Comment by ionelmc** [comment]
There are some examples with classes in the examples section https://python-aspectlib.readthedocs.io/en/latest/examples.html
