### ISSUE TITLE
[Q] Is it still alive?

### ISSUE THREAD

**Issue by s-kostyuk** [ionelmc/python-aspectlib#8]
Good day

Looks like this library wasn't updated for last two years just as well some other libraries with a similar purpose. So, here is the question: is this project still alive? Can it be recommended for usage in new projects? And if not, why everybody suddenly decided to abandon AOP libraries for Python (i.e. what is an alternative approach to the usage of AOP libraries)?

**Comment by ionelmc** [comment]
What other libraries are you referring to? 

So I have only two issues, neither of them are really bad bugs - they are more like feature requests. Does that make the project dead?

The alternative to AOP? Write good code that don't need AOP. Aspectlib exposes AOP for what it really is: glorified monkeypatching :)

**Comment by s-kostyuk** [comment]
I'm referring to alecthomas/aspect (last updated 6 years ago), python-aop (last updated 5 years ago), aspyct (officially closed [in 2012](http://aspyct.org/aspyct/)), b3j0f/aop (last updated a year ago), baris/pyaspects (last updated in 2013) and spring-python (more than just an AOP framework, but anyway; last updated in 2014). So, there are a lot of AOP frameworks which development was frozen between 2013 and 2016 by some reason.

So, thank you for a fast response! This question is closed

**Comment by ionelmc** [comment]
So the "other libraries" updated in the last two years is just **one** library, and the author would not compare it to aspectlib. Ok :-)

**Comment by s-kostyuk** [comment]
Actually, I was trying to say that a lot of libraries are suddenly stopped their development in the last years, including this library. I wasn't meant that "all other libraries are already updated but this is not", just wandering about a general situation :). Sorry for my English.
